### ISSUE TITLE
deCONZ 6.2.1 ingress.html not found

### ISSUE THREAD

**Issue by basdejong95** [home-assistant/hassio-addons#1516] opened 2020-07-29 11:55 UTC
Hi, i just installed the version 6.2.1 of deCONZ. However, in the home assistant menu when i go to the addon, it says: 

This is not the page you are looking for
The file /ingress.html couldn't be found.

How can i downgrade or fix this?

**Comment by ludeeus** [comment] 2020-08-03 08:12
To downgrade an addon you need to do a partial restore from a snapshot that has an earlier version.
Closing this as this is not a bug.

If you have any questions reach out on the forums or on Discord.
https://www.home-assistant.io/help/

**Closed by ludeeus** 2020-08-03 08:12 UTC
Labels: add-on: deconz
