### ISSUE TITLE
configurator can't use

### ISSUE THREAD

**Issue by shom** [home-assistant/hassio-addons#1092] opened 2020-02-18 08:53 UTC
docker logs 

```txt
INFO:2020-02-18 16:50:14,097:hass_configurator.configurator:Starting server
INFO:2020-02-18 16:50:14,098:hass_configurator.configurator:Listening on: http://0.0.0.0:8099
INFO:2020-02-18 16:50:22,566:hass_configurator.configurator:172.30.32.2 - "GET / HTTP/1.1" 200 -
INFO:2020-02-18 16:50:51,580:hass_configurator.configurator:172.30.32.2 - "GET / HTTP/1.1" 200 -
INFO:2020-02-18 16:50:53,075:hass_configurator.configurator:172.30.32.2 - "GET / HTTP/1.1" 200 -
INFO:2020-02-18 16:50:54,437:hass_configurator.configurator:172.30.32.2 - "GET / HTTP/1.1" 200 -
INFO:2020-02-18 16:51:04,847:hass_configurator.configurator:172.30.32.2 - "GET / HTTP/1.1" 200 -
INFO:2020-02-18 16:51:14,197:hass_configurator.configurator:172.30.32.2 - "GET / HTTP/1.1" 200 -
INFO:2020-02-18 16:51:37,447:hass_configurator.configurator:172.30.32.2 - "GET / HTTP/1.1" 200 -
INFO:2020-02-18 16:52:10,721:hass_configurator.configurator:172.30.32.2 - "GET / HTTP/1.1" 200 -
INFO:2020-02-18 16:52:11,586:hass_configurator.configurator:172.30.32.2 - "GET /material-icons.fallback.css HTTP/1.1" 200 -
CRITICAL:2020-02-18 16:52:11,589:hass_configurator.configurator:[Errno 2] No such file or directory: '/usr/local/lib/python3.7/site-packages/hass_configurator/material-icons.fallback.css'
INFO:2020-02-18 16:52:11,599:hass_configurator.configurator:172.30.32.2 - "GET /style.css HTTP/1.1" 200 -
CRITICAL:2020-02-18 16:52:11,602:hass_configurator.configurator:[Errno 2] No such file or directory: '/usr/local/lib/python3.7/site-packages/hass_configurator/style.css'
INFO:2020-02-18 16:52:11,660:hass_configurator.configurator:172.30.32.2 - "GET /jquery-3.4.1.min.js HTTP/1.1" 200 -
INFO:2020-02-18 16:52:11,664:hass_configurator.configurator:172.30.32.2 - "GET /materialize.min.js HTTP/1.1" 200 -
CRITICAL:2020-02-18 16:52:11,666:hass_configurator.configurator:[Errno 2] No such file or directory: '/usr/local/lib/python3.7/site-packages/hass_configurator/jquery-3.4.1.min.js'
CRITICAL:2020-02-18 16:52:11,667:hass_configurator.configurator:[Errno 2] No such file or directory: '/usr/local/lib/python3.7/site-packages/hass_configurator/materialize.min.js'
INFO:2020-02-18 16:52:11,700:hass_configurator.configurator:172.30.32.2 - "GET /js-yaml.min.js HTTP/1.1" 200 -
CRITICAL:2020-02-18 16:52:11,702:hass_configurator.configurator:[Errno 2] No such file or directory: '/usr/local/lib/python3.7/site-packages/hass_configurator/js-yaml.min.js'
```

**Comment by frenck** [comment] 2020-02-18 09:05
duplicate of #1093

**Closed by frenck** 2020-02-18 09:05 UTC
Labels: add-on: configurator
