### ISSUE TITLE
file editor problem

### ISSUE THREAD

**Issue by formatta2003** [home-assistant/hassio-addons#1096] opened 2020-02-18 10:01 UTC
INFO:2020-02-18 10:50:09,441:hass_configurator.configurator:172.30.32.2 - "GET /js-yaml.min.js HTTP/1.1" 200 -
CRITICAL:2020-02-18 10:50:09,442:hass_configurator.configurator:[Errno 2] No such file or directory: '/usr/local/lib/python3.7/site-packages/hass_configurator/js-yaml.min.js'

**Comment by frenck** [comment] 2020-02-18 10:03
Duplicate of #1093 

Please update to 4.5.

**Closed by frenck** 2020-02-18 10:03 UTC
