### ISSUE TITLE
Deconz: Unable to start after upgrade 6.1

### ISSUE THREAD

**Issue by fleshyflat** [home-assistant/hassio-addons#1486] opened 2020-07-21 07:39 UTC
After I upgrade to 6.1 Deconz is unable to start. The follow error is in the log

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] firmware.sh: executing... 
/usr/bin/GCFFlasher_internal.bin: error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory
[cont-init.d] firmware.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[09:34:48] INFO: 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] vnc.sh: executing... 
[cont-init.d] vnc.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[07:34:49] INFO: Running the deCONZ OTA updater...
[07:34:49] INFO: Starting udevd...
[services.d] done.
[09:34:49] INFO: Waiting for device...
[07:34:49] INFO: Running the IKEA OTA updater...
[07:34:49] INFO: Running the OSRAM LEdvance OTA updater...

[09:34:57] INFO: Starting VNC server...
[09:35:02] INFO: Waiting for VNC to start
[09:35:02] INFO: Starting the deCONZ gateway...
deCONZ: error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory
readlink: write error: Broken pipe
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

**Comment by frenck** [comment] 2020-07-21 07:51
Duplicate of #1480 and #1485 

Please upgrade to version 6.1.1 of the add-on where this was fixed in.

**Closed by frenck** 2020-07-21 07:51 UTC
