### ISSUE TITLE
Add on "Deconz" can not start ,after Deconz 6.0 /6.1 upgrade

### ISSUE THREAD

**Issue by leoyangt** [home-assistant/hassio-addons#1485] opened 2020-07-20 22:35 UTC
Dear All:
    For Add on  Deconz.
    "Deconz" can not start ,after Deconz 6.0 /6.1 upgraded.
    Deconz was ok before version 6.0
    I run supervised in Raspberry Pi4 and conbee-2.
Below is log 

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] firmware.sh: executing... 
[06:30:54] INFO: GCFFlasher V3_13 (c) dresden elektronik ingenieurtechnik gmbh
Path             | Vendor | Product | Serial     | Type
-----------------+--------+---------+------------+-------
/dev/ttyACM0     | 0x1CF1 | 0x0030  |            | ConBee II 
/dev/ttyAMA0     | 0x0000 | 0x0000  |            | RaspBee 
[cont-init.d] firmware.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] vnc.sh: executing... 
[cont-init.d] vnc.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[22:30:54] INFO: Running the deCONZ OTA updater...
[22:30:54] INFO: Running the IKEA OTA updater...
[22:30:54] INFO: Running the OSRAM LEdvance OTA updater...
[22:30:54] INFO: Starting udevd...
[06:30:54] INFO: Waiting for device...
[06:31:01] INFO: Starting VNC server...

[06:31:05] INFO: Waiting for VNC to start
[06:31:05] INFO: Starting the deCONZ gateway...
qt.qpa.screen: QXcbConnection: Could not connect to display :0
Could not connect to any X display.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

**Comment by frenck** [comment] 2020-07-20 22:59
Duplicate of #1480 

This issue has been fixed in add-on version 6.1.1

**Closed by frenck** 2020-07-20 22:59 UTC
