### ISSUE TITLE
deCONZ - FATAL: No device since 3.4 / 3.5

### ISSUE THREAD

**Issue by mcfrojd** [home-assistant/hassio-addons#685] opened 2019-09-03 15:18 UTC
Today i updated deCONZ addon first to 3.4 and then to 3.5
On both new versions i get this error when i try to start the addon.

`[16:52:47] FATAL: No device /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE1962254-if00 found!
`
That device path shows under "hassio/system/hardware" and worked on addon version 3.3

I have tried to change the device to this diffrent ones (one by one) but they give same error.
"/dev/ttyUSB0"
"/dev/ttyUSB1"
"/dev/ttyAMA0"
"/dev/ttyAMA1"
"/dev/ttyACM0"
"/dev/ttyACM1"

Restoring from snapshot to 3.3 makes it work again

**Comment by KennethLavrsen** [comment] 2019-09-03 16:43
Hi. I have the same issue. But you can make it work with /dev/ttyACM#. But you have to restart Home Assistant. It is not enough to restart the addon.

This is really annoying. I was so happy when the addon was changed so it accept the by-id links as my Aeotec and Conbee randomly swap between 0 and 1 when I reboot the host machine. 

We need that restored again. It is important that you can use these /dev/serial/by-id/blabla links so things are predictable and reliable.

**Comment by KennethLavrsen** [comment] 2019-09-03 17:01
@pvizeli it seems you did the change that broke the use of /dev/serial/by-id links. We had been begging for this feature and finally got it a month or so ago. It would be really good if you would fix your latest changes so it works again. You cannot rely on direct /dev/tty links and you all the normal udev tricks do not work as they also create symlinks that don't work.

**Comment by pvizeli** [comment] 2019-09-03 20:34
Can't see any issue with Supervisor 185 and docker 18.09 or 19.03

**Comment by mattias1972** [comment] 2019-09-03 20:48
My deCONZ addon also broke when updating from 3.3 to 3.5, refuses to start.
Log entrys:
2019-09-03 21:31:23 ERROR (MainThread) [.] Error connecting to deCONZ gateway at 172.30.32.1
2019-09-03 21:31:23 WARNING (MainThread) [homeassistant.config_entries] Config entry for deconz not ready yet. Retrying in 5 seconds.

**Comment by pvizeli** [comment] 2019-09-03 20:52
what say the dmesg after start?

**Comment by mattias1972** [comment] 2019-09-03 21:00
This is the complete dmesg from last boot, there are an awful lot of entrys about the conbee…

 

//Mattias

 

Från: Pascal Vizeli <notifications@github.com>
Svara till: home-assistant/hassio-addons <reply@reply.github.com>
Datum: tisdag 3 september 2019 22:52
Till: home-assistant/hassio-addons <hassio-addons@noreply.github.com>
Kopia: Mattias Hemborg <mattias@hemborg.eu>, Comment <comment@noreply.github.com>
Ämne: Re: [home-assistant/hassio-addons] deCONZ - FATAL: No device since 3.4 / 3.5 (#685)

 

what say the dmesg after start?

**Comment by KennethLavrsen** [comment] 2019-09-03 21:05
I think the original reporter did not restart HA but only the addon when he reported that it does not work with any device. I can make it work with /dev/ttyACM1.
We may want the original reporter to verify that it works for him if he restarts the entire HA installation.

What is broken is using the /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_.......

The error message is that it cannot find this device. It worked fine until I upgraded to the 3.5 (from 3.3).  

In the bare metal host the by-id link is present still.

**Comment by pvizeli** [comment] 2019-09-03 21:11
![image](https://user-images.githubusercontent.com/15338540/64209080-e1819a80-ce9f-11e9-89f1-55269e7a63d7.png)

The question is, what is different on your baremetal setup. Tested with docker 18.09 and 19.03 / supervisor 185 -> HassOS, Debian, Ubuntu 18.04 (Desktop)

**Comment by pvizeli** [comment] 2019-09-03 21:14
@mattias1972 docker is not plug&play. If you plug out the stick at back again, you need restart the add-on, but the device is block by docker and it create a time a new ttyUSBx. Try a full host reboot to become a clean state

**Comment by mattias1972** [comment] 2019-09-03 21:27
> @mattias1972 docker is not plug&play. If you plug out the stick at back again, you need restart the add-on, but the device is block by docker and it create every time a new ttyUSBx. Try a full host reboot to become a clean state

It still refuses to start despite a reboot of the Pi. dmesg shows fewer entrys about the combee but still there are 10 of them this beeing the last one:
77.051689] usb 1-1.1.2: USB disconnect, device number 10
[   77.401865] usb 1-1.1.2: new full-speed USB device number 11 using dwc_otg
[   77.536208] usb 1-1.1.2: New USB device found, idVendor=1cf1, idProduct=0030
[   77.537386] usb 1-1.1.2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[   77.539587] usb 1-1.1.2: Product: ConBee II
[   77.540730] usb 1-1.1.2: Manufacturer: dresden elektronik ingenieurtechnik GmbH
[   77.542019] usb 1-1.1.2: SerialNumber: DE1996448
[   77.545521] cdc_acm 1-1.1.2:1.0: ttyACM0: USB ACM device

**Comment by KennethLavrsen** [comment] 2019-09-03 21:32
I have triple checked again and I have this config

```
{
  "device": "/dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE1962724-if00",
```

and I get the error

```
starting version 237

[23:21:48] FATAL: No device /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE1962724-if00 found!
```

And extra check that I use the correct device
```

root@homeassistant:/dev/serial/by-id# ls -al
total 0
drwxr-xr-x 2 root root 80 Sep  3 23:31 .
drwxr-xr-x 4 root root 80 Sep  3 22:48 ..
lrwxrwxrwx 1 root root 13 Sep  3 23:17 usb-0658_0200-if00 -> ../../ttyACM0
lrwxrwxrwx 1 root root 13 Sep  3 23:31 usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE1962724-if00 -> ../../ttyACM1
```

**Comment by mkarnebeek** [comment] 2019-09-03 21:42
Same here. Broke when updating from 3.3 to 3.5 with the same stick. Using `/dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE1995908-if00` which is there, even within the container.

**Comment by pvizeli** [comment] 2019-09-04 07:52
> Tested with docker 18.09 and 19.03

Since no one gives details about his installation, I would suggest that you have the wrong docker installed and not docker-ce.

**Comment by mkarnebeek** [comment] 2019-09-04 08:18
This is hassio, latest everything, except for home assistant itself (0.97.2), and deconz addon (3.3). Let me know where in hassio you'd like to have a dump for more formation about internals (docker, etc.)

As far as I can see from the UI, i've gathered the following info:
- hassio supervisor 185
- via Portainer, I've discovered i'm running Docker Standalone 18.09.4

**Comment by pvizeli** [comment] 2019-09-04 08:34
docker-ce? BaseOS?

**Comment by pvizeli** [comment] 2019-09-04 08:57
I had setup now a new ubuntu core 18.04. Install all dependencies and docker-ce (From docker repository). Everythings work with "/dev/serial/by-id/usb-FTDI_FT230X_Basic_UART_DM01H1ID-if00-port0"

I can't help here. I think there is an issue on setup. There was an update how the supervisor spinup itels. Maybe you run the old service files. Execute:
`curl -sL https://raw.githubusercontent.com/home-assistant/hassio-installer/master/hassio_install.sh | sudo bash -s`

to update the installation and restart the server. That could help

**Comment by KennethLavrsen** [comment] 2019-09-04 13:28
I think we have several populations here.

1. From #680 people that already had the issue before the 3.4/3.5 update
2. People that get an error that device is not ready yet
3. And then we are at least 3 or 4 that have the situation where the by-id link does not work in 3.5 but works in 3.3

They should probably be split on 3 bug reports

I am only addressing case 3 which is what seems to best fit the original report.

I surely run docker-ce. I had upgraded to the latest 0.98.2 before the upgrade of deconz and it worked. I know because when it fails all my automatic light stops working so I would have noticed

Mine broke down the minute I upgraded the deconz addon from 3.3 to 3.5 (did not see the 3.4 update) and to get it back I had to use the straight /dev/ttyACM# link

When I look at the host Ubuntu I notice that udev create symbolic links from /dev/serial/by-id that point back to /dev
When I use the ssh within HA the docker view of things are that /dev/serial/by-id/device_name are "files" and not links. I do not know if this means anything but it is an observation

I also have an Aeotec Z-wave stick using ZHA. 

It is configured and WORKS like this

```
zwave:
  usb_path: /dev/serial/by-id/usb-0658_0200-if00
  network_key: !secret zwave_network_key
```

So for the zwave integration the by-id works fine.

In the Home Assistant hass.io -> Host System -> Hardware button I can the the two by-id devices

The error message from deconz is "FATAL: No device /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE1962724-if00 found!"

This is the same error you get if you put some complete nonsense.

The conclusion I have so far that this seems to be an isolated problem to the deconz docker container. Inside this the by-id devices do not exist. We need to find out why. If we go back a few versions of deconz it did not work either. Then the feature was introduced so you could use by-id links. And now it is broken again. And it happens in a release where udev was dramatically chanced as far as I can see in the code without understanding what is it that happens. It seems some udev related stuff was change to using a python based library. But I do not know Python so I am a bit lost

**Comment by KennethLavrsen** [comment] 2019-09-04 13:39
You say everything works with Everythings work with "/dev/serial/by-id/usb-FTDI_FT230X_Basic_UART_DM01H1ID-if00-port0"

That is not a deconz device. They are not getting named like that. It is ONLY in deconz things fail. It works just fine in ZHA. A deconz device name has dresden_elektronik_ingenieurtechnik_GmbH in them

**Comment by KennethLavrsen** [comment] 2019-09-04 16:54
Just came home from work so I could access the HA machine from command line.

I tried the script https://raw.githubusercontent.com/home-assistant/hassio-installer/master/hassio_install.sh and restarted server - it made no difference

I then tried to restore a snapshot of HA but I kept all current and only restored deconz 3.1. I did not have a snap with 3.3 sorry. But when I restore deconz 3.1 it works again with the 'by-id' device. And when I upgrade deconz back to latest it breaks again. It cannot be a setup or docker version issue. And it is not related to the changes in hass.io done recently. It is isolated to deconz. 3.1 works. 3.5 fails to use by-id links. I have to use simple /dev/tty devices again to make it work.

**Comment by mattias1972** [comment] 2019-09-04 17:21
Five reboots later deCONZ addon suddenly has decided to work again. I have no idea what was wrong and no clue why it works again... Maybe my Conbee II is faulty, only time will tell, for the moment everything work again.

**Comment by pvizeli** [comment] 2019-09-04 18:40
@KennethLavrsen I have all devices from deCONZ. The ID above was a Conbe1.

I'm wrong, after rerunning the installation, you need to destroy the supervisor container to start a rebuild with new parameters. `docker rm hassio_supervisor`.

I close the issue after I tested it on a HassOS, Debian, Ubuntu with a fresh installation and with latest installer scripts. There is no Python, because it's a complex system between Linux kernel, udev bus, and docker as it is. This work only with "latest" spinup of supervisor. If you run the supervisor container with an older setup before 5 month, there is an issue with trigger reload of udev devices overall containers they are listening to the linux kernel bus.

**Closed by pvizeli** 2019-09-04 18:40 UTC

**Comment by KennethLavrsen** [comment] 2019-09-04 19:08
@balloob I want to complain about how this issue is treated. We are several people with the same issue and there is no resolution.

I will reopen new issue with same content

**Comment by KennethLavrsen** [comment] 2019-09-04 19:27
And for the record
I have done all suggestions so far and I just did the docker rm hassio_supervisor
And I reran the install script.

And it still fails the same way.

It is not correct to close an issue after so short time when several people are reporting the same issue. I can understand if it is one socker that refuse to try anything. But we are multiple people with same issue and there is obvious an issue caused by the changes in deconz 3.5

I will also say that mattias1972 reported a completely different symptom and his resolution has nothing to do with the issue originally reported.

The least one can do is revert the changes back to what actually worked until we understand what goes wrong.

**Comment by KennethLavrsen** [comment] 2019-09-05 06:44
I continue gathering info.

I read up on docker and now I know how to create a bash session on a running container.

And to my surprise I can find /dev/serial/by-id/usb-... links to both sticks and they are symlinks and they point to the right place.

So I tried again to change the deconz config to the by-id device and restarted deconz only. And it worked. Why? What? So I tried to see if this was a lasting fixed by itself situation. No it is not! After a restart of HA I am back to not working with same error message. The container was then manually started and it worked. And then tried many boots of the entire metal machine as well as HA. It works every 3rd time or so.

It seems to be a timing issue. Maybe udev is not done running before deconz is started and trying to access the device. It is a "no device found" error. Not access denied or device busy or similar. So my best guess now is that either udev does not always succeed creating the by-id symlinks or it does it too late. I need advice how to debug this further.

@pvizeli will you be so kind and reopen this so we do not discuss this on a github issue that soon freezes for comments?

**Comment by KennethLavrsen** [comment] 2019-09-05 07:06
I am trying to figure out what is going on at start. But I do not understand how the docker thing works. I am a docker noob obviously.

I can see in my /usr/share/hassio/addons/core/deconz/data directory that there is a run.sh that seems to be a bash script that start up deconz. But it is obviously not this script that runs because when I edit the file no change is done. There is a 3 second delay I would like to increase to 5 or 10 to see if it makes a difference. How do I get this change made effective?

**Comment by KennethLavrsen** [comment] 2019-09-05 16:54
I have been working half the night yesterday, reading HA dev documentation at work, and worked several hours today trying to debug this. I am stuck at how to modify the run.sh script and rebuild the deconz image with the change. I have asked on Discord in the dev_general channel but noone has been there today that could help.

I really tried to understand the addon development documentation and I tried many things that all failed.

I need help to pass the point where I am stuck. I really want to participate and spend the hours debugging and root causeing this and I respect that it is impossible for @pvizeli to fix something he cannot reproduce. But I can reproduce it here. If I restart deconz 10 times it fails 50% of the time. It can work 5 times in a row and fail 5 times in a row. But it is 50/50 that it fails or start normally with by-id device. I have a theory that the delay of 3 seconds may not be enough in some cases. It can also be that udev fails to create the symlink. To find out what it is I need to be able to alter and add debug echos to the run.sh script 

I just cannot find out how to get the docker container rebuilt with my changes. I do not understand how it works. I need help. A one liner - this is how to rebuild the container picking up the altered run.sh is what I need. Please

**Comment by KennethLavrsen** [comment] 2019-09-05 21:43
I gave up on using the Home Assistant Addon version of deconz.

I found that it was dead easy to install deconz from the original Debian repository. Then it updates every time I do apt upgrade. Much easier. And it runs on bare metal. No docker shit. So no more worries about devices swapping around. So if someone else want to escalate this issue then go ahead. I am done. I also moved mqtt and other things back to bare metal some time ago.

**Comment by mkarnebeek** [comment] 2019-09-05 21:58
I've just locked this addon on 3.3 and will not be updating it anymore. My vacation starts tomorrow, so i'll be out for a while. Hopefully this will eventually get fixed.

**Comment by KennethLavrsen** [comment] 2019-09-10 11:40
Another with same issue

https://community.home-assistant.io/t/deconz-official-thread/100504/577

Sad that the developer refuses to fix it and assume we are all wrong

**Comment by frenck** [comment] 2019-09-10 13:16
I think your last comment (the last line) is completely unnecessary, disrespectful and not called for @KennethLavrsen.

Sorry to hear you are having issues, but without a reproduction scenario, it will be hard for anyone to fix (as you've said yourself earlier). Both me and Pascal have a large number of (different) test systems. On none of those, it is reproducible.

This has nothing to do with refusing to fix it.

**Comment by KennethLavrsen** [comment] 2019-09-10 13:55
@frenck

I think closing an issue claiming there is no issue is equally disrespectful to all the people with the problem.  And then repeating it again to a new user closing exactly same issue one more time.

And I am sorry for only being a human with human feelings. I got upset. In the official deconz forum topic there are new people that reported the same issue. It affects many people.

I spent more than 20 hours trying to debug the problem but I got stuck because I still do not understand how to rebuild a docker after changing the script that runs when it starts. I tried to get help in the dev channels on discord but noone was present to help me.

I can see that there is a 3 second delay in the script and my current theory is that the new way of running udev takes more than the 3 seconds on some computers depending on how much hardware that needs to be discovered.

I tried to read the dev docs carefully but I know too little about dockers to understand how to rebuild the containers with changed content. I tried many things but always end up with the original code running with the 3 second delay

I fixed MY immediate issue by moving to a non Home Assistant solution (bare metal). I am trying to help the other users that try to use the HA addon now.

The way forward that I suggest is

- Reopen this bug
- Try and build the addon changing the 3 second delay to a wait for the serial device to be existing - with a timeout of maybe 30 or 60 seconds so the addon can die if the device was defined wrong by the user
- Release this as an update even if you cannot confirm it fixes the issue and ask the people that reported the issue to come back with feedback if it fixes it.
