### ISSUE TITLE
Workday Binary Sensor is missing Estonia

### ISSUE THREAD

**Issue by wjaceh** [home-assistant/hassio-addons#855] opened 2019-11-23 20:41 UTC
Workday Binary Sensor is missing Estonia [EE] option.
In python-holidays library it exists:
[https://github.com/dr-prodigy/python-holidays#available-countries](url)

**Comment by frenck** [comment] 2019-11-23 21:40
Duplicate of: https://github.com/home-assistant/home-assistant/pull/29000

**Closed by frenck** 2019-11-23 21:40 UTC
