### ISSUE TITLE
There is not history in mariadb after HA update

### ISSUE THREAD

**Issue by anglrus** [home-assistant/hassio-addons#1408] opened 2020-06-14 07:59 UTC
Hello,
MariaDB does not save history and doen't show on graph after last HA updates.
Log is OK.
Config is:

databases:
  - homeassistant
logins:
  - username: hass
    host: '%'
    password: password
rights:
  - username: hass
    host: '%'
    database: homeassistant
    grant: ALL PRIVILEGES ON

recorder.yaml:

db_url: mysql://hass:password@core-mariadb/homeassistant?charset=utf8
purge_keep_days: 7
auto_purge: true

**Comment by comatose-tortoise** [comment] 2020-06-14 10:59
Same thing happened here. Updated from 0.111.0 to 0.111.2 and all history (including all history recorded before the update) from MariaDB is empty. Checking the DB with phpMyAdmin shows that nothing new has been recorded since the update. All current values are reported fine, i.e., temp sensors show a correct current temperature that is updated fine, but nothing is recorded.

**Comment by frenck** [comment] 2020-06-14 16:09
Duplicate of https://github.com/home-assistant/frontend/issues/6161

PR to fix this: https://github.com/home-assistant/core/pull/36769

**Closed by frenck** 2020-06-14 16:09 UTC
