### ISSUE TITLE
Google Assistant SDK - "(invalid_grant) Bad Request" on initial authentication

### ISSUE THREAD

**Issue by adamtal3** [home-assistant/hassio-addons#654] opened 2019-08-11 10:04 UTC
After defining the project according to the instructions inside the Google Actions Console I try to start the Google Assistant SDK so my HA can act as a hub with a mic & speaker.

Going though the app authentication (clicking the authenticate, selecting my google account, approving my project app and copying the token back to the Google Assistant SDK web page) I get an error log for: `oauthlib.oauth2.rfc6749.errors.InvalidGrantError`.

This is the complete log from the addon:

```
[Info] Install/Update service client_secrets file
[Info] Start WebUI for handling oauth2
[11/Aug/2019:12:51:21] ENGINE Listening for SIGTERM.
[11/Aug/2019:12:51:21] ENGINE Listening for SIGHUP.
[11/Aug/2019:12:51:21] ENGINE Listening for SIGUSR1.
[11/Aug/2019:12:51:21] ENGINE Bus STARTING
CherryPy Checker:
The Application mounted at '' has an empty config.
[11/Aug/2019:12:51:21] ENGINE Started monitor thread 'Autoreloader'.
[11/Aug/2019:12:51:21] ENGINE Serving on http://0.0.0.0:9324
[11/Aug/2019:12:51:21] ENGINE Bus STARTED
192.168.1.1** - - [11/Aug/2019:12:51:21] "GET / HTTP/1.1" 200 713 "" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36"
[11/Aug/2019:12:52:08] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/cherrypy/_cprequest.py", line 628, in respond
    self._do_respond(path_info)
  File "/usr/local/lib/python3.6/dist-packages/cherrypy/_cprequest.py", line 687, in _do_respond
    response.body = self.handler()
  File "/usr/local/lib/python3.6/dist-packages/cherrypy/lib/encoding.py", line 219, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/hassio_oauth.py", line 46, in token
    self.oauth2.fetch_token(self.user_data['token_uri'], client_secret=self.user_data['client_secret'], code=token)
  File "/usr/local/lib/python3.6/dist-packages/requests_oauthlib/oauth2_session.py", line 307, in fetch_token
    self._client.parse_request_body_response(r.text, scope=self.scope)
  File "/usr/local/lib/python3.6/dist-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 415, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "/usr/local/lib/python3.6/dist-packages/oauthlib/oauth2/rfc6749/parameters.py", line 425, in parse_token_response
    validate_token_parameters(params)
  File "/usr/local/lib/python3.6/dist-packages/oauthlib/oauth2/rfc6749/parameters.py", line 432, in validate_token_parameters
    raise_from_error(params.get('error'), params)
  File "/usr/local/lib/python3.6/dist-packages/oauthlib/oauth2/rfc6749/errors.py", line 405, in raise_from_error
    raise cls(**kwargs)
oauthlib.oauth2.rfc6749.errors.InvalidGrantError: (invalid_grant) Bad Request
[11/Aug/2019:12:52:08] HTTP 
Request Headers:
  Remote-Addr: 192.168.1.1**
  HOST: 192.168.1.1**:9324
  CONNECTION: keep-alive
  PRAGMA: no-cache
  CACHE-CONTROL: no-cache
  UPGRADE-INSECURE-REQUESTS: 1
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
  ACCEPT: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3
  REFERER: http://192.168.1.1**:9324/
  ACCEPT-ENCODING: gzip, deflate
  ACCEPT-LANGUAGE: he-IL,he;q=0.9,en-US;q=0.8,en;q=0.7
192.168.1.1** - - [11/Aug/2019:12:52:08] "GET /token?token=4%2FnQHAMK_*********zA****Uw8*********2****9a******nw HTTP/1.1" 500 2486 "http://192.168.1.1**:9324/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36"
[11/Aug/2019:12:52:12] ENGINE SystemExit raised: shutting down HTTP server
[11/Aug/2019:12:52:12] ENGINE Bus STOPPING
[11/Aug/2019:12:52:12] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 9324)) shut down
[11/Aug/2019:12:52:12] ENGINE Stopped thread 'Autoreloader'.
[11/Aug/2019:12:52:12] ENGINE Bus STOPPED
[11/Aug/2019:12:52:12] ENGINE Bus EXITING
[11/Aug/2019:12:52:12] ENGINE Bus EXITED
[11/Aug/2019:12:52:12] ENGINE Waiting for child threads to terminate...
[Info] Run Hass.io GAssisant SDK
```

After this error - every time I start the addon and try to open the web UI I get a connection error page and if I open the web UI or not after a couple of minutes the addon stops without any log messages.

Here is my addon page and settings:
![image](https://user-images.githubusercontent.com/3287937/62832634-20725680-bc3a-11e9-98e8-462249795db6.png)

The "google_assistant.json" file is located in the "/share" folder as instructed and here is how it looks (I've only tried changing the redirect_uris hoping to solve this issue but everything else is as downloaded from the credentials page):
![image](https://user-images.githubusercontent.com/3287937/62832680-ea81a200-bc3a-11e9-9157-50a973aa009d.png)

How can I find the reason for the invalid_grant error which I'm guessing is returned from Google and not the addon?

**Comment by adamtal3** [comment] 2019-09-10 11:34
No suggestions on this? I still can't use the Google Assistant locally on my raspberry pi..

**Comment by yevon** [comment] 2019-09-15 21:42
I'm having this exact issue also, what happens with that?. And after initial setup, you cannot open web ui menu again, you have to uninstall the plugin and install it again. It was working nicely weeks ago, and now I can't login.

**Comment by yevon** [comment] 2019-09-15 22:12
My assistant started working again without needing to re-authenticate. I just went to the google actions console, I added the english language to the project, and started the google actions test mode multiple times, then I restarted the plugin and it started working again. Then I realized that there were more problems, because with the voice command "sync my devices", it wasn't able to connect to the home assistant. The last error can be fixed with just re-adding home assistant test project to the google assistant accounts.

**Comment by adamtal3** [comment] 2019-09-16 08:35
> My assistant started working again without needing to re-authenticate. I just went to the google actions console, I added the english language to the project, and started the google actions test mode multiple times, then I restarted the plugin and it started working again. Then I realized that there were more problems, because with the voice command "sync my devices", it wasn't able to connect to the home assistant. The last error can be fixed with just re-adding home assistant test project to the google assistant accounts.

I already had English and running the test mode didn't help running this plugin.
After you got it working again - what do you see when you open the Web UI? Is it still an error? Or does it indicate that it works again?

**Comment by yevon** [comment] 2019-09-16 19:35
The log just says this:

[Info] Install/Update service client_secrets file
[Info] Run Hass.io GAssisant SDK

I discovered that it was my mistake, I didn't have the router ports redirected to the IP of the home assistant server, I deleted some port redirection by accident. You need a home assistant with SSL acces mandatory, and double check that the IP and port for access from google to your home assistant is accessible from the internet. You must put https://yourdomain:yourport/api/google_assistant

![image](https://user-images.githubusercontent.com/121157/64987579-c6fce780-d8c9-11e9-8eaa-1ad563ef3018.png)

**Comment by adamtal3** [comment] 2019-09-16 23:02
@yevon - Thanks for trying to help but I have HA accessible via SSL with a valid certificate and it's set with `/api/google_assistant` in the fulfillment URL in the actions console.
The plugin still won't start.

What did you set for the `model_id` in the configuration of the plugin?

Another thing that's annoying here is that logs are completely empty (both the plugin logs and the HA logs).

**Comment by yevon** [comment] 2019-09-17 20:00
Yeah, maybe your problem is the model_id. I rembember to become crazy finding this option also, because documentation doesn't say anything about it.

You have to go to this URL in the google actions console:, and register a new model_id. In my case it is not accessible by any menu:

 **[https://console.actions.google.com/u/0/project/{your-project-name}/deviceregistration](/)**

**Comment by yevon** [comment] 2019-10-28 15:43
The problem is solved adding the proper model_id using the URL i said in prior comment. Anyways, I endend up buying a google home mini for just 30$, because this tool is already not properly maintained. I think this can be closed isn't it?

**Closed** 2019-12-04 16:09 UTC
Labels: add-on: google_assistant, wontfix

**Comment by boyfromgermany** [comment] 2020-02-25 20:53
this still seems to be an issue

**Comment by ericmatte** [comment] 2020-05-02 17:23
> Yeah, maybe your problem is the model_id. I rembember to become crazy finding this option also, because documentation doesn't say anything about it.
> 
> You have to go to this URL in the google actions console:, and register a new model_id. In my case it is not accessible by any menu:
> 
> **[https://console.actions.google.com/u/0/project/{your-project-name}/deviceregistration](/)**

That is probably because you've added an action to your project.
I've found that as soon as you add an action, the "Device Registration" link is removed from the UI.

Before adding an action:
<img src="https://user-images.githubusercontent.com/9013072/80870978-f05f5d80-8c77-11ea-8666-4efc7c46bb86.png" alt="Example 1" width="250">

After:
<img src="https://user-images.githubusercontent.com/9013072/80870992-fce3b600-8c77-11ea-8cb9-3c0da49691d2.png" alt="Example 1" width="250">

**Comment by ericmatte** [comment] 2020-05-02 17:34
> You must put https://yourdomain:yourport/api/google_assistant as seen below
> 
> ![image](https://user-images.githubusercontent.com/121157/64987579-c6fce780-d8c9-11e9-8eaa-1ad563ef3018.png)

My add-on was also not working, and I thought that this could be the problem. After multiple tests, I've found that this was not needed in order for it to work.
In my case, Google Assistant was actually working, but the sound was way too low.

I simply said "Ok Google, set volume to maximum.", and that fixed my add-on.
