### ISSUE TITLE
DECONZ and high CPU usage

### ISSUE THREAD

**Issue by dedepene** [home-assistant/hassio-addons#996] opened 2020-01-13 08:44 UTC
After I realized my hass.io server is under unusually high load it turned out the deconz container accounted for this. Apparently this has been going on for quite a few hours and after I restarted the addon from within HA it's all back to normal. 

How do I keep troubleshooting this to figute out what triggers deconz to quadruple it's CPU usage?

[https://ibb.co/Kbbn4V4](https://ibb.co/Kbbn4V4)

**Comment by pvizeli** [comment] 2020-01-13 09:58
If you see that again, can you look at which process exactly consumes this? If that one of our shell scripts, we can fix it otherwise we need to report it to deconz itself.

**Comment by dedepene** [comment] 2020-01-13 10:00
> If you see that again, can you look at which process exactly consumes this? If that one of our shell scripts, we can fix it otherwise we need to report it to deconz itself.

will do, but how do I look this up?

**Comment by Luke95vl** [comment] 2020-01-13 18:06
I noticed the same behavior in my VM with HassOS, the assigned cores go to 60% while they usually stay on 8/10%

If I stop the addon and restart it returns to normal but after a couple of hours it returns

**Comment by dedepene** [comment] 2020-01-13 18:19
> I noticed the same behavior in my VM with HassOS, the assigned cores go to 60% while they usually stay on 8/10%
> 
> If I stop the addon and restart it returns to normal but after a couple of hours it returns

10 hours later it's still looking good.

https://ibb.co/XbrLyDQ

**Comment by pvizeli** [comment] 2020-01-14 08:37
You can use `top` on host or inside add-on to see which process eat this

**Comment by dedepene** [comment] 2020-01-23 19:09
So I had another incident today, all the zigbee devices were super unresponsive as well. Nothing of note while looking at "top" inside the container. However, this was in the log. As soon as I restarted the addon from within HA - everything back to normal.

```
2020-01-23 17:28:46 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 576, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/components/deconz/light.py", line 173, in async_turn_on
    await self._device.async_set_state(data)
  File "/usr/local/lib/python3.7/site-packages/pydeconz/deconzdevice.py", line 41, in async_set_state
    await self.async_set(field, data)
  File "/usr/local/lib/python3.7/site-packages/pydeconz/deconzdevice.py", line 48, in async_set
    await self._request("put", field, json=data)
  File "/usr/local/lib/python3.7/site-packages/pydeconz/gateway.py", line 110, in request
    ) from None
pydeconz.errors.RequestError: Error requesting data from 172.30.33.1: [Errno 104] Connection reset by peer
```

**Comment by pvizeli** [comment] 2020-01-24 14:44
I can't confirm this issue. What kind of platform/hardware do you use?

**Comment by dedepene** [comment] 2020-01-24 14:56
> I can't confirm this issue. What kind of platform/hardware do you use?

I run hassio on Ubuntu 18.04.2 itself on a bare-metal Lenovo M92p Tinly (INtel G2020T, 4GB RAM).

**Comment by pvizeli** [comment] 2020-01-24 14:58
So you run the amd64 version of the addon. I think @Luke95vl too

**Comment by dedepene** [comment] 2020-01-24 15:06
> So you run the amd64 version of the addon. I think @Luke

i guess...

**Comment by Luke95vl** [comment] 2020-01-24 15:18
> So you run the amd64 version of the addon. I think @Luke95vl too

Yes, amd64

I have not had other occasions to verify the problem because in these days I have restarted home Assistant and the server many times

**Comment by frenck** [comment] 2020-01-24 16:04
I run the amd64 (2 instances actually) and do not experience this.

**Comment by dedepene** [comment] 2020-02-09 13:19
This is still a thing. Unfortunately, I didn't get a chance to examine closely i.e. look up processes - had to restart deconz addon instantly.

https://ibb.co/vPthhrh

**Comment by fi-sch** [comment] 2020-02-12 20:57
Same here on RPi 4...
<img width="576" alt="Zrzut ekranu 2020-02-12 o 21 56 25" src="https://user-images.githubusercontent.com/59969726/74376531-95d60400-4de2-11ea-91c4-8e2d878506cc.png">

**Comment by fi-sch** [comment] 2020-02-13 07:50
After 11-12 hours it's still there eating around the same amount of CPU and memory. I'm not a unix guy, soI don't know how to debug that by myself.
I tried restarting the add-on, restarting HASS and even host itself but the problem still persist.

**Comment by dedepene** [comment] 2020-02-13 08:01
> After 11-12 hours it's still there eating around the same amount of CPU and memory. I'm not a unix guy, so I don't know how to debug that by myself.
> I tried restarting the add-on, restarting HASS and even host itself but the problem still persist.
> 
> That's nasty because my RPi is heating up to 70+ celsius because of that issue and it's just above the acceptable threshold.

That's weird. Over here CPU use drops back to normal levels as soon as I restart the deconz addon.

**Comment by fi-sch** [comment] 2020-02-13 09:25
Restarting it a few times did not help for me. It helped when I totally stopped the add-on, waited for a couple of seconds and then restarted HASS (add-on is set to start automatically with HA).

**Comment by fi-sch** [comment] 2020-02-13 17:18
Same thing again after 7-8 hours of operating normally.

**Comment by fi-sch** [comment] 2020-02-18 14:26
Just to let you know. It happened again just before Supervisor version 201 release. Stop/start of deCONZ add-on helped. Let's see how long it will last with the new Supervisor.

**Comment by pvizeli** [comment] 2020-02-18 14:44
The issue is a single process inside the Phoscon App. Any supervisor updates or other updates did not help. The only people they can fix that issue is Dresden Electronics and we can just update to new release if there is an new release. So any kind of discusion here is like hot/cool air.

**Comment by fi-sch** [comment] 2020-02-18 15:04
> The issue is a single process inside the Phoscon App. Any supervisor updates or other updates did not help. The only people they can fix that issue is Dresden Electronics and we can just update to new release if there is an new release. So any kind of discusion here is like hot/cool air.
> 
> thanks for the top screenshots and that look excatly what I said.

Ok, thanks. I have just written an e-mail to Dresden Elektronik support :)

**Comment by frenck** [comment] 2020-02-18 17:38
Closing this issue for now, because of the above reasoning.

**Closed by frenck** 2020-02-18 17:38 UTC
Labels: add-on: deconz, amd64
