### ISSUE TITLE
HASS.IO addon upgrade to 6.1.1 error

### ISSUE THREAD

**Issue by andysaab** [home-assistant/hassio-addons#1487] opened 2020-07-21 08:29 UTC
After upgrade addon got error - deCONZ: error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory
![Deconz error](https://user-images.githubusercontent.com/56047524/88031555-6d96c200-cb45-11ea-9945-9da530412afa.jpg)
Restore from backup and work again sucsessefully.

**Comment by frenck** [comment] 2020-07-21 09:16
Could you provide details on your setup? Hardware? 32 or 64 bits?

**Comment by andysaab** [comment] 2020-07-21 09:43
Thx for your reply, Frenk!
My setup is Xpenology on HP Gen8
![image](https://user-images.githubusercontent.com/56047524/88038964-a50a6c00-cb4f-11ea-98e8-e3684d5869cb.png)

**Comment by fleshyflat** [comment] 2020-07-21 10:44
same problem her with 6.1.1

**Comment by althaus** [comment] 2020-07-22 13:14
I've got the same error. System is Hassio running on a Synology DS via Docker.

System health is same as andysaab's one besides HA 0.112.4 and Python 3.7.7.

**Comment by og9gjz567** [comment] 2020-07-23 11:26
I've got the same error. System is Hassio running on a Synology DS via Docker, too.
I'm currently running version 0.112.4 ;)

**Comment by omersh82** [comment] 2020-07-23 12:00
Same error for me, running hassio on Synology DS via docker.

2020-07-23 08:43:01 | stderr | [11:43:00] INFO: [32mStarting VNC server...[0m
2020-07-23 08:43:01 | stderr | [11:43:00] INFO: [32mWaiting for device...[0m
2020-07-23 08:43:01 | stderr | [08:43:00] INFO: [32mRunning the deCONZ OTA updater...[0m
2020-07-23 08:43:01 | stderr | [08:43:00] INFO: [32mRunning the IKEA OTA updater...[0m
2020-07-23 08:43:01 | stderr | [08:43:00] INFO: [32mStarting udevd...[0m
2020-07-23 08:43:00 | stderr | [08:43:00] INFO: [32mRunning the OSRAM LEdvance OTA updater...[0m
2020-07-23 08:43:00 | stdout | [services.d] done.
2020-07-23 08:42:59 | stdout | [services.d] starting services
2020-07-23 08:42:59 | stdout | [cont-init.d] done.
2020-07-23 08:42:59 | stdout | [cont-init.d] vnc.sh: exited 0.
2020-07-23 08:42:59 | stdout | [cont-init.d] vnc.sh: executing...
2020-07-23 08:42:59 | stdout | [cont-init.d] nginx.sh: exited 0.
2020-07-23 08:42:57 | stdout | [cont-init.d] nginx.sh: executing...
2020-07-23 08:42:57 | stdout | [cont-init.d] firmware.sh: exited 0.
2020-07-23 08:42:57 | stderr | [11:42:57] INFO: [32m[0m
2020-07-23 08:42:57 | stderr | /usr/bin/GCFFlasher_internal.bin: error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory
2020-07-23 08:42:56 | stdout | [cont-init.d] firmware.sh: executing...
2020-07-23 08:42:56 | stdout | [cont-init.d] executing container initialization scripts...
2020-07-23 08:42:56 | stdout | [fix-attrs.d] done.
2020-07-23 08:42:56 | stdout | [fix-attrs.d] applying ownership & permissions fixes...
2020-07-23 08:42:56 | stdout | [s6-init] ensuring user provided files have correct perms...exited 0.
2020-07-23 08:42:55 | stdout | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.

Thanks

**Comment by jlvandusen** [comment] 2020-07-24 01:28
I too have the same issue.. infuriating... as this is appears to be broken on delivery.
I am running Synology Docker image on my DS1517+

here is my errors (same as everyone else)  - we need a way to revert this image back to last which I believe was 5.3.5.
`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] firmware.sh: executing... 
/usr/bin/GCFFlasher_internal.bin: error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory
[21:06:37] INFO: 
[cont-init.d] firmware.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] vnc.sh: executing... 
[cont-init.d] vnc.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[01:06:38] INFO: Running the deCONZ OTA updater...
[01:06:38] INFO: Running the OSRAM LEdvance OTA updater...
[21:06:38] INFO: Waiting for device...
[01:06:38] INFO: Running the IKEA OTA updater...
[01:06:38] INFO: Starting udevd...
[21:06:38] INFO: Starting the deCONZ gateway...
deCONZ: error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.`

**Comment by jlvandusen** [comment] 2020-07-24 03:25
I was able to use the snapshots within Synology,
Stopped Redrike+hassio synology package (Im using his package to run hass.io)
image

Stopped Docker
I then found the last good snapshot of my docker folder for hass.io
I restored and overwrote the current folder containing the deconz 6.11 which btw is located under /docker/hass.io/addons/data/core_deconz
(*where docker is the volume where I have the hass.io and other docker containers pointing to)
I then started docker
I went and stopped all hassio containers
I deleted all containers related to hassio
I then removed all images related to hassio
I started fredrike’s synology package - it did its part downloading and re-creating all the primary containers to run homeassistant
Once Home assistant was back up and running
I went into supervisor
I selected deconz
it showed I was originally running 5.3.6
I then went back to docker
downloaded homeassistant/addon_deconz 5.3.6
once downloaded, I mounted it
I named the container addon_core_deconz
I clicked on advance
I set its volume to the below path
/data = /docker/hass.io/addons/data/core_deconz
I did not start it
I went back to homeassistant UI and into supervisor
I then started deconz
It started…
after a few moments my sensors were back online!

**Comment by og9gjz567** [comment] 2020-07-24 06:51
@jlvandusen I Tihink there is a simpler way: I use hassio on Synology Docker, too. I went to the ha supervisor tab and selected one of my last snapshots. There you can choose only to restore deCONZ. After a few minutes my deCONZ was up and running again (5.3.6)

**Comment by mpolivanov** [comment] 2020-07-24 08:04
For those with an old snapshot like me:

docker container rm <id of deconz 6.1.1 container>
docker image rm homeassistant/amd64-addon-deconz:6.1.1 (use --force if necessary)
docker pull homeassistant/amd64-addon-deconz:5.3.6
docker tag homeassistant/amd64-addon-deconz:5.3.6 homeassistant/amd64-addon-deconz:6.1.1

Start addon from HA web interface. It is by far not the cleanest approach, but it works for me

**Comment by andysaab** [comment] 2020-07-24 08:30
For my opinion is an easiest way to restore addon`s functionality - restore ONLY Deconz addon from previous snapshot via Supervisor Snapshots page.
@frenck Is there any news on how to solve this problem?

**Comment by frenck** [comment] 2020-07-24 08:32
As for all the reports mentioned, are you all running supervised on synology?

**Comment by fleshyflat** [comment] 2020-07-24 08:38
hi Frenck, no I have an CentOs with docker on ESX

**Comment by omersh82** [comment] 2020-07-24 08:39
i am running on Synology with hassio on docker

**Comment by mpolivanov** [comment] 2020-07-24 08:44
Synology 716 with hassio package

**Comment by andysaab** [comment] 2020-07-24 08:44
i am running on Synology with hassio on docker too.

**Comment by frenck** [comment] 2020-07-24 09:04
![image](https://user-images.githubusercontent.com/195327/88376239-46d2c880-cd9d-11ea-8e04-cc4c6f3ef838.png)

The issue occurs on systems that are not supported by the Home Assistant project. We'll look into bypassing this, but even with that in place, please be aware, that your system is actually not suited for running Home Assistant and not suite to run deCONZ as well.

Your Conbee stick will not be able to upgrade firmware for example.

**Comment by pvizeli** [comment] 2020-07-24 09:11
The issue is the kernel is to old for the binary ELF.
https://github.com/Microsoft/WSL/issues/3023#issuecomment-452339739

Also reported on other linux distro. There is a workaround to stripe ABI part out of ELF which require this kernel version. We look into to fix that for older kernel to give compatibtle with unsupported systems.

**Comment by jlvandusen** [comment] 2020-07-24 10:53
> @jlvandusen I Tihink there is a simpler way: I use hassio on Synology Docker, too. I went to the ha supervisor tab and selected one of my last snapshots. There you can choose only to restore deCONZ. After a few minutes my deCONZ was up and running again (5.3.6)

I would agree - however, I don't snap within HA I snap my volumes at the block level.

**Comment by pvizeli** [comment] 2020-07-24 11:02
@jlvandusen your system is not supported and looks like the Linux kernel has issues with a new binary ABI level. Means, you will have this issue next time more often. You should run a supported system or freeze what you run and never update again.

**Comment by pvizeli** [comment] 2020-07-24 11:08
I close this PR now follow up of:
https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md

All systems with this issue are not supported by us. Feel free to create a fork of this add-on and merge my closed PR to fix it partially. However, all QT builts higher as 5.10 need at least a Linux kernel >= 3.17.

**Closed by pvizeli** 2020-07-24 11:08 UTC
Labels: add-on: deconz

**Comment by althaus** [comment] 2020-07-24 11:49
I understand the decision, but it's a pity as there a many folks out there successfully running HA on a Synology this way. :(

**Comment by omersh82** [comment] 2020-07-24 12:26
Is there a way to revert back even if i don't have a snapshot?

**Comment by jlvandusen** [comment] 2020-07-24 12:33
@pvizeli agreed- I could run THE SUPPORTED HA on Synology without supervision... however having the supervisor is key here though.  So I used fredrikes workaround...
You do show support for docker and synology in the installation guides...
https://www.home-assistant.io/docs/installation/docker/

**Comment by frenck** [comment] 2020-07-24 14:05
Our container-based installation (docker guides you linked) does not include the supervisor or add-ons @jlvandusen. The ADR linked above by Pascal shows exactly what is supported, the method by fredrikes to run a Supervised system on a Synology is not supported and will cause issues.

**Comment by fleshyflat** [comment] 2020-07-24 14:08
I have replace my installation from Centos with docker to HassOS and now its working perfect with version 6.1.1

**Comment by labaland** [comment] 2020-07-24 18:08
Synology user here too :(

**Comment by omersh82** [comment] 2020-07-24 18:24
i just installed the conbee as a standalone docker, had to re-add the sensor but now there is no dependency on the hassio

**Comment by labaland** [comment] 2020-07-24 18:31
> i just installed the conbee as a standalone docker, had to re-add the sensor but now there is no dependency on the hassio

Do you mean this one ? : https://registry.hub.docker.com/r/marthoc/deconz

**Comment by omersh82** [comment] 2020-07-24 18:49
> > i just installed the conbee as a standalone docker, had to re-add the sensor but now there is no dependency on the hassio
> 
> Do you mean this one ? : https://registry.hub.docker.com/r/marthoc/deconz

yes

**Comment by jlvandusen** [comment] 2020-07-24 18:55
Did it actually install 6.1.1 as a docker container on Synology right?

James

**Comment by omersh82** [comment] 2020-07-24 18:57
> Did it actually install 6.1.1 as a docker container on Synology right? James From: omersh82<mailto:notifications@github.com> Sent: Friday, July 24, 2020 2:49 PM To: home-assistant/hassio-addons<mailto:hassio-addons@noreply.github.com> Cc: James VanDusen<mailto:jlvandusen@msn.com>; Mention<mailto:mention@noreply.github.com> Subject: Re: [home-assistant/hassio-addons] HASS.IO addon upgrade to 6.1.1 error (#1487) i just installed the conbee as a standalone docker, had to re-add the sensor but now there is no dependency on the hassio Do you mean this one ? : https://registry.hub.docker.com/r/marthoc/deconz<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fregistry.hub.docker.com%2Fr%2Fmarthoc%2Fdeconz&data=02%7C01%7C%7C0781bb3a2d154be667e108d83002526c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637312133807609230&sdata=JB7ltNH%2FpvgfoxRTUycZyaCo8%2FcwALy1bSbJR3dh9iY%3D&reserved=0> yes — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fhome-assistant%2Fhassio-addons%2Fissues%2F1487%23issuecomment-663681981&data=02%7C01%7C%7C0781bb3a2d154be667e108d83002526c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637312133807609230&sdata=g%2F3tWXXOlXRUa4TGxjbiIZxsTSKrg7FE41TIizS5CVo%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FADTO3YGOWCVJ3MA6AXUODC3R5HJUHANCNFSM4PDJ63HA&data=02%7C01%7C%7C0781bb3a2d154be667e108d83002526c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637312133807609230&sdata=eUPc%2F1s1WpqTUpmKW61XDd1ikLnMK%2FrRwipwnTJB1KI%3D&reserved=0>.

yes, and add it as an integration to ha with the internal ip it got from the docker

**Comment by labaland** [comment] 2020-07-24 21:01
Works for me now. But how do i check if i have the newest version of deconz? omhersh82 ?

**Comment by jlvandusen** [comment] 2020-07-24 21:23
It should be shown on the container... when in docker?

**Comment by labaland** [comment] 2020-07-24 22:45
> It should be shown on the container... when in docker?

[marthoc/deconz] Current deCONZ version: 2.05.79

**Comment by pvizeli** [comment] 2020-07-24 23:22
Just for lowering the happiness, we updated the library inside container because deconz updated the glibc which here binary blobs are built again. If marthoc fix the issues because some components stop to work, you end up in same issue, or short never update also that container because the next version can include the new glibc fix and it leads on the same issue now. Try to become a kernel update for your system is the only longterm fix

**Comment by labaland** [comment] 2020-07-24 23:37
> Just for lowering the happiness, we updated the library inside container because deconz updated the glibc which here binary blobs are built again. If marthoc fix the issues because some components stop to work, you end up in same issue, or short never update also that container because the next version can include the new glibc fix and it leads on the same issue now. Try to become a kernel update for your system is the only longterm fix

Ok :( is sry for my noob question.. Is Raspberry Pi 4 B (2gb) the best device to host HA on? everything will always work there?

**Comment by bgmn** [comment] 2020-07-25 20:46
> For those with an old snapshot like me:
> 
> docker container rm <id of deconz 6.1.1 container>
> docker image rm homeassistant/amd64-addon-deconz:6.1.1 (use --force if necessary)
> docker pull homeassistant/amd64-addon-deconz:5.3.6
> docker tag homeassistant/amd64-addon-deconz:5.3.6 homeassistant/amd64-addon-deconz:6.1.1
> 
> Start addon from HA web interface. It is by far not the cleanest approach, but it works for me

Did you manually create a container from the image after tag command? And if you did, what parameters did you use?
All I'm seeing is the old 6.1.2 version on supervisor panel.

**Comment by mpolivanov** [comment] 2020-07-26 07:28
> Did you manually create a container from the image after tag command? And if you did, what parameters did you use?
> All I'm seeing is the old 6.1.2 version on supervisor panel.

no, it is created automatically by surevisor

**Comment by mpepping** [comment] 2020-07-26 19:16
Newer Synology models ship with the 4.4 kernel instead of the 3.10 or even 3.2 kernel. 
Doesn't change the fact that it's an unsupported configuration to run HA supervised though. 


https://www.reddit.com/r/synology/comments/cz8xse/kernel_4459_on_dsm_62/

**Comment by bgmn** [comment] 2020-07-26 19:55
I'm installing Ubuntu server on Synology virtual machine manager and configuring Docker on it. That way I would have new kernel on Docker host and run Home assistant without legacy problems. I'm afraid how much will the overhead of virtual machine slow things down.

**Comment by jlvandusen** [comment] 2020-07-26 23:55
I ended up enabling VMM on my 1517+ and then downloaded THE SUPPORTED VMDK version and proceeded to migrate over my configuration to that... with 100% success.... now running Deconz 6.12 now with full support.

**Comment by bgmn** [comment] 2020-07-27 06:18
> I ended up enabling VMM on my 1517+ and then downloaded THE SUPPORTED VMDK version and proceeded to migrate over my configuration to that... with 100% success.... now running Deconz 6.12 now with full support.

Right after installing Ubuntu, Docker and Home Assistant, I noticed the supported VMDK version. 😀

**Comment by Nick1100** [comment] 2020-07-27 07:18
How to run it corecley on donker om Synology itself via supervisor itself? 


deCONZ: error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory

There must be a way to solve this error

**Comment by jlvandusen** [comment] 2020-07-27 13:00
> How to run it corecley on donker om Synology itself via supervisor itself?
> 
> deCONZ: error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory
> 
> There must be a way to solve this error

Depending upon the synology you have, please try to run the VMDK version in using VMM from synology.  Once you have it up and running, you can simply copy the backup or if you can see the files, copy the files from the docker and overwrite the deployed version running under VMM.... it will essentially migrate your config to the VMM version and you can use the latest Deconz etc...
