### ISSUE TITLE
Mosquitto broker SSL error - Missing documentation

### ISSUE THREAD

**Issue by denics** [home-assistant/hassio-addons#1550] opened 2020-08-26 17:27 UTC
## The problem
Dear all,
I am trying to use Mosquitto using the official addon. In the docs it is mentioned that it is possible to disable connection to insecure port 1883 (what about 8883?) and listen to 1884. In the example it is shown how to configure certfile and
keyfile. However, my noob question is: 

*how can I create the key in hassio?*

## Environment
- Add-on with the issue: Mosquitto broker
- Add-on release with the issue: NA
- Last working add-on release (if known): NA
- Operating environment (OS/Supervised): Hass.io

## Problem-relevant configuration
Default conf

```yaml
logins: []
anonymous: false
customize:
  active: false
  folder: mosquitto
certfile: fullchain.pem
keyfile: privkey.pem
require_certificate: false
```

## Traceback/Error logs
```txt
[19:11:26] INFO: Setup mosquitto configuration
[19:11:26] WARNING: SSL not enabled - No valid certs found!
[19:11:26] INFO: No local user available
[19:11:27] INFO: Initialize Hass.io Add-on services
[19:11:27] INFO: Initialize Home Assistant discovery
[19:11:27] INFO: Start Mosquitto daemon
```

**Comment by denics** [comment] 2020-08-29 13:34
This is linked to #1412 , closed without an answer.

**Comment by ludeeus** [comment] 2020-08-30 08:10
This is not an issue with the addon, or it's documentation.
You should already have the certs before trying to use it.

Since this is not a bug/issue here, I'm closing it.

For support please reach out on the [forums](https://community.home-assistant.io/) or [discord](https://discord.gg/c5DvZ4e)
Thanks :+1:

**Closed by ludeeus** 2020-08-30 08:10 UTC

**Comment by denics** [comment] 2020-08-30 21:00
Thank you @ludeeus, can you then point me and the author of #1412 to the section where we can find info about this on the documentation?
