### ISSUE TITLE
IKEA Blind Not working

### ISSUE THREAD

**Issue by Puntoboy** [home-assistant/hassio-addons#1461] opened 2020-07-14 09:19 UTC
Did @frenck actually read my issue before closing? The Issue happens with the WebApp! It's not just an issue with Home Assistant, that is simply talking to Deconz. If I try and use the device in the Phoscon WebApp it doesn't work either! How is this an issue with core?

In the last couple of days, by IKEA blind has stopped responding.

I have factory reset the blind, re-paired it to Deconz, and recharged the battery. Nothing has worked. I then tried updating Deconz to the latest but that hasn't helped either.

I can see the device in VNC and on the web app. but if I try to adjust it from the web app or from home assistant nothing happens. On Home Assistant I get a "Failed to call service cover/close_cover. /lights/2 resource, /lights/2, not available" and on Node-Red I get an API error.

I'm running my system in Docker. It has been working fine for a while.

If I manually call the "cover" service in HA, I see this error in the logs:

![image](https://user-images.githubusercontent.com/11718878/87408190-057f3380-c5bb-11ea-989f-24965d0e20ec.png)

I also see this in the logs constantly.

![image](https://user-images.githubusercontent.com/11718878/87408201-0c0dab00-c5bb-11ea-9bd4-099e89bc5592.png)

Also, in VNC, the device is sitting with a green flashing indicator. All other devices flash blue.

![image](https://user-images.githubusercontent.com/11718878/87408348-3cede000-c5bb-11ea-882e-7068c7c98c84.png)

How can I troubleshoot please? The logs for the add-on don't really show much..

![image](https://user-images.githubusercontent.com/11718878/87408515-79b9d700-c5bb-11ea-83ee-7794e03d66e5.png)

**Comment by frenck** [comment] 2020-07-14 09:23
@Puntoboy Yes, I read issues and closed it because if was misplaced. So is this one again.

It is either core or the deCONZ web app.

Add-ons wrap existing applications, we do not write those here. Considering your error message in from the HA core, I think the HA core would be a good start. If you think the issue is with the deCONZ application, please file an issue with deCONZ/dresden.

In case dresden fixes it and a new version of the app is released, the add-on will be updated as well.

You can find their issues tracker here: <https://github.com/dresden-elektronik/deconz-rest-plugin/issues>

Thanks 👍

**Closed by frenck** 2020-07-14 09:23 UTC

**Comment by Puntoboy** [comment] 2020-07-14 09:25
This is silly. I follow the link from the add-on and it brings me here. If I have to post elsewhere for these issues why does it bring me here?

**Comment by frenck** [comment] 2020-07-14 11:47
It depends on the issue. There are many moving parts in a system like this.

I'm seriously not amused by a 👎 . I'm trying to help by pointing you in the right direction. Would you have been happier if I have let the issue open and let is be unresolved forever?

**Comment by Mimiix** [comment] 2020-07-14 17:51
@frenck His issue relied in the fact that dev/ttyacm* as serial device breaks things.  New users should be adviced to only use the hardware serial (as mentioned in the addon, yet people don't read it). 

That being said, user didn't read our documentation on updating either as updating the firmware in a VM is strongly discouraged.

It's solved for now.

**Comment by Puntoboy** [comment] 2020-07-14 17:57
> 
> 
> @frenck His issue relied in the fact that dev/ttyacm* as serial device breaks things. New users should be adviced to only use the hardware serial (as mentioned in the addon, yet people don't read it).
> 
> That being said, user didn't read our documentation on updating either as updating the firmware in a VM is strongly discouraged.
> 
> It's solved for now.

I don't agree at all with that.

The addon documentation says I can use either path for the device and that was only changed AFTER the other issues as I was trying to fix the issue

![image](https://user-images.githubusercontent.com/11718878/87459440-4e5ada80-c603-11ea-8caf-d2c34032e000.png)


The IKEA Blind issue also happened before any other issues, just that single device. As part of troubleshooting that I tried to update the addon and firmware. The Addon update worked and the firmware did not (through the addon). I tried updating through Windows (which didn't work either) so I tried a UB VM, which said it worked but seemingly did not. I tried windows again (after your recommendation) and Windows worked this time. It was after that the device path was changed to dev/ttyACM. 


After all this I'm not entirely sure why the IKEA blind stopped responding, but it does not work and I didn't need to re-pair it again.

**Comment by Puntoboy** [comment] 2020-07-14 17:58
Also to note, using the full device path lists my device as a RaspBee and not a ConBeeII. 

![image](https://user-images.githubusercontent.com/11718878/87459950-fe304800-c603-11ea-955d-01b29eef7423.png)

**Comment by frenck** [comment] 2020-07-14 18:40
> His issue relied in the fact that dev/ttyacm* as serial device breaks things. New users should be adviced to only use the hardware serial

As a matter of fact, functional there is no difference, so I don't get your reply.

> RaspBee and not a ConBeeII

This has been a reported at and ignored bug by dresden.

**Comment by Mimiix** [comment] 2020-07-14 18:42
I have no clue why it happens, but when they change to that serial it suddenly gets fixed. 

Do you mean this issue? https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1798

**Comment by manup** [comment] 2020-07-14 19:31
>The IKEA Blind issue also happened before any other issues, just that single device. As part of troubleshooting that I tried to update the addon and firmware. The Addon update worked and the firmware did not (through the addon). I tried updating through Windows (which didn't work either) so I tried a UB VM, which said it worked but seemingly did not. I tried windows again (after your recommendation) and Windows worked this time. It was after that the device path was changed to dev/ttyACM.

Hi, everybody. It's not yet clear why the blind get lost sometimes but there are some ideas to be tested.
I'm getting a IKEA blind this week from the company and will have a closer look in the Zigbee sniffer to see what's going on.

As usual there must be a reason for this.

Since problem needs to be fixed in deCONZ core/REST-API please continue discussion in https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3044

**Comment by Puntoboy** [comment] 2020-07-14 19:34
The blind stopping working wasn’t my concern so much. It was that it couldn’t re-add it even after factory resetting it, charging the battery and rebooting everything.
