### ISSUE TITLE
Deconz 5.3.3 using inside Home Assistant no longer allowing Hue bulbs to transition to off when using Node Red

### ISSUE THREAD

**Issue by Hicko16** [home-assistant/hassio-addons#1341] opened 2020-05-23 21:36 UTC
Hello,

As the subject suggests, I have just updated to Deconz 5.3.3 which runs inside my Home Assistant. I currently have nodes configured in Node Red, so when my motion sensors stop detecting motion they transition to off within 300 seconds (5 minutes). Unfortunately, now as soon as motion stops the lights go off instantly when using 5.3.3. They all worked perfectly with the previous versions of Deconz. Not sure what has happened but it is very strange. I also have three Lifx bulbs and they still transition correctly using the same nodes.

Thanks.

Adam

**Comment by frenck** [comment] 2020-05-24 08:21
Duplicate of https://github.com/home-assistant/core/issues/36018

**Closed by frenck** 2020-05-24 08:21 UTC
