### ISSUE TITLE
OZW - crashes HassOS on boot

### ISSUE THREAD

**Issue by Dinth** [home-assistant/hassio-addons#1562] opened 2020-09-02 18:24 UTC
## The problem

Im running HassOS on ESXi host. 
If i restart HassOS VM after a significant uptime, it fails to boot because of OZW addon. 
Restarting whole ESXi hosts

## Environment

- Add-on with the issue: OZW
- Add-on release with the issue: 0.5.2
- Last working add-on release (if known): N/A
- Operating environment (OS/Supervised): HassOS

## Traceback/Error logs

Apologies for the  screenshot but i couldnt copy and paste from a headless server.
![Screenshot from 2020-09-02 19-05-42](https://user-images.githubusercontent.com/313674/92021606-f3677900-ed51-11ea-914a-86fe6e5e837c.png)

**Comment by Dinth** [comment] 2020-09-03 19:03
Update - doesnt seem to be limited to HassOS boot, today it crashed whole HassOS in the middle of a day with same message.

**Comment by lrybak** [comment] 2020-10-03 06:57
I have similar, don't have logs but my hassos running as a Proxmox vm is very unstable. it crashed vm few times already

**Comment by soleen** [comment] 2020-10-19 22:56
Seems to be dup of [https://github.com/home-assistant/hassio-addons/issues/1474](issue 1474)

**Comment by MartinHjelmare** [comment] 2020-10-20 01:10
Duplicate of #1474

**Closed by MartinHjelmare** 2020-10-20 01:10 UTC
Labels: add-on: zwave
