### ISSUE TITLE
File Editor (Configurator) doesn't start anymore

### ISSUE THREAD

**Issue by EkielZan** [home-assistant/hassio-addons#1095] opened 2020-02-18 09:54 UTC
Hi,

I've just updated to the new version of configuratro/File Editor and I can't use it anymore.
The loading circle is spinning endelessly.

Here are the logs of the containers ( i'm using Hass.io  docker style)

CRITICAL:2020-02-18 09:52:00,568:hass_configurator.configurator:[Errno 2] No such file or directory: '/usr/local/lib/python3.7/site-packages/hass_configurator/material-icons.fallback.css'
INFO:2020-02-18 09:52:00,580:hass_configurator.configurator:172.30.32.2 - "GET /style.css HTTP/1.1" 200 -
CRITICAL:2020-02-18 09:52:00,583:hass_configurator.configurator:[Errno 2] No such file or directory: '/usr/local/lib/python3.7/site-packages/hass_configurator/style.css'
INFO:2020-02-18 09:52:01,332:hass_configurator.configurator:172.30.32.2 - "GET /jquery-3.4.1.min.js HTTP/1.1" 200 -
CRITICAL:2020-02-18 09:52:01,334:hass_configurator.configurator:[Errno 2] No such file or directory: '/usr/local/lib/python3.7/site-packages/hass_configurator/jquery-3.4.1.min.js'
INFO:2020-02-18 09:52:01,363:hass_configurator.configurator:172.30.32.2 - "GET /materialize.min.js HTTP/1.1" 200 -
CRITICAL:2020-02-18 09:52:01,365:hass_configurator.configurator:[Errno 2] No such file or directory: '/usr/local/lib/python3.7/site-packages/hass_configurator/materialize.min.js'
INFO:2020-02-18 09:52:01,894:hass_configurator.configurator:172.30.32.2 - "GET /js-yaml.min.js HTTP/1.1" 200 -
CRITICAL:2020-02-18 09:52:01,895:hass_configurator.configurator:[Errno 2] No such file or directory: '/usr/local/lib/python3.7/site-packages/hass_configurator/js-yaml.min.js'

**Comment by frenck** [comment] 2020-02-18 09:57
Duplicate of #1093 

Please update to 4.5

**Closed by frenck** 2020-02-18 09:57 UTC

**Comment by EkielZan** [comment] 2020-02-18 10:13
My bad. Didn't see the other issues about that
