### ISSUE TITLE
Rest API endpoints are not available after 4.1 update

### ISSUE THREAD

**Issue by adamkanovak** [home-assistant/hassio-addons#933] opened 2019-12-21 06:49 UTC
http://hassio:40860/api/apikey/sensors
is not available anymore. 
I use some put requests to configure the duration of my motion sensors. I guess the ingress support has something to do with this.

**Comment by frenck** [comment] 2019-12-21 07:32
Duplicate of #931 and #926, extensively discussed in #926 

Please make sure to check for existing issues before creating a new one, thanks! 👍

**Closed by frenck** 2019-12-21 07:32 UTC
