### ISSUE TITLE
Deconz keep shutting down

### ISSUE THREAD

**Issue by sandert98** [home-assistant/hassio-addons#824] opened 2019-11-11 09:10 UTC
Hi there,

I don't know the exact moment, but since I have upgraded to Home Assistant 0.101 and Deconz to 3.7, I had a lot of stability issues. The lights where responding very slow, or not at all. Thats why I uninstalled the Deconz add-on and re-installed it. But, when starting the Deconz addon, it keeps shutting down. 

Deconz  config:
```{
  "device": "/dev/ttyACM0",
  "vnc_password": "",
  "dbg_aps": 1
}
```

Deconz log:

```09:57:27:560 create 117C-11C2-12248572
09:57:27:585 create 117C-0002-165801BC
09:57:27:615 create 117C-4203-20022623
09:57:27:619 found node plugin: libstd_otau_plugin.so - STD OTAU Plugin
09:57:27:645 dev /dev/ttyAMA0
09:57:27:645 COM: /dev/ttyACM0 / serialno: DE1998083
09:57:27:645 COM: --dev: /dev/ttyACM0 (ConBee II)
09:57:27:756 wait reconnect 15 seconds
09:57:27:782 dev /dev/ttyAMA0
09:57:27:782 COM: /dev/ttyACM0 / serialno: DE1998083
09:57:27:782 COM: --dev: /dev/ttyACM0 (ConBee II)
09:57:28:755 wait reconnect 14 seconds
09:57:29:757 wait reconnect 13 seconds
09:57:30:755 wait reconnect 12 seconds
09:57:31:755 wait reconnect 11 seconds
09:57:32:221 dev /dev/ttyAMA0
09:57:32:756 wait reconnect 10 seconds
09:57:32:905 Announced to internet
09:57:32:905 discovery server date: Mon, 11 Nov 2019 08:57:32 GMT
09:57:32:906 	 local time seems to be ok
09:57:32:906 discovery found version 2.04.35 for update channel stable
09:57:33:755 wait reconnect 9 seconds
09:57:34:581 New websocket 192.168.100.107:55472 (state: 3) 
09:57:34:755 wait reconnect 8 seconds
09:57:35:756 wait reconnect 7 seconds
09:57:36:755 wait reconnect 6 seconds
09:57:36:756 scan skip host .178
09:57:37:583 New websocket 192.168.100.9:40926 (state: 3) 
09:57:37:755 wait reconnect 5 seconds
09:57:38:161 don't close database yet, keep open for 900 seconds
09:57:38:756 wait reconnect 4 seconds
09:57:39:755 wait reconnect 3 seconds
09:57:40:755 wait reconnect 2 seconds
09:57:41:755 wait reconnect 1 seconds
09:57:41:818 dev /dev/ttyAMA0
09:57:41:818 COM: /dev/ttyACM0 / serialno: DE1998083
09:57:41:818 COM: --dev: /dev/ttyACM0 (ConBee II)
09:57:42:281 dev /dev/ttyAMA0
09:57:42:281 GW update firmware found: /usr/share/deCONZ/firmware/deCONZ_ConBeeII_0x26490700.bin.GCF
09:57:42:755 wait reconnect 15 seconds
09:57:42:823 dev /dev/ttyAMA0
09:57:42:823 COM: /dev/ttyACM0 / serialno: DE1998083
09:57:42:823 COM: --dev: /dev/ttyACM0 (ConBee II)
09:57:43:755 wait reconnect 14 seconds
09:57:44:755 wait reconnect 13 seconds
09:57:45:755 wait reconnect 12 seconds
09:57:46:755 wait reconnect 11 seconds
09:57:46:755 start reconnect to network
09:57:47:457 scan skip host .132
This plugin does not support propagateSizeHints()
QXcbConnection: Could not connect to display 
09:57:47:756 wait reconnect 10 seconds
09:57:48:755 wait reconnect 9 seconds
09:57:49:756 wait reconnect 8 seconds
09:57:50:755 wait reconnect 7 seconds
09:57:51:755 wait reconnect 6 seconds
09:57:52:005 failed to reconnect to network try=1
09:57:52:756 wait reconnect 5 seconds
09:57:53:755 wait reconnect 4 seconds
09:57:54:755 wait reconnect 3 seconds
09:57:55:756 wait reconnect 2 seconds
09:57:56:755 wait reconnect 1 seconds
09:57:56:824 dev /dev/ttyAMA0
09:57:56:824 COM: /dev/ttyACM0 / serialno: DE1998083
09:57:56:824 COM: --dev: /dev/ttyACM0 (ConBee II)
09:57:56:879 Device firmware version 0x264A0700
09:57:56:894 unlocked max nodes: 200
09:57:56:965 Device protocol version: 0x010B
09:57:56:971 new node - ext: 0x00212effff048b9a, nwk: 0x0000
09:57:56:984 CTRL [00:0d:6f:ff:fe:c7:d7:90] not viable in zll.db, skip load cache (101)
09:57:57:030 Current channel 15
09:57:57:035 APS-DATA.request id: 4, addrmode: 0x02, addr: 0x0000, profile: 0x0000, cluster: 0x0002, ep: 0x00 -> 0x00 queue: 0 len: 3 tx.options 0x04
09:57:57:046 CTRL ANT_CTRL 0x03
09:57:57:070 Device protocol version: 0x010B
09:57:57:118 Current channel 15
09:57:57:134 CTRL ANT_CTRL 0x03
09:57:57:166 APS-DATA.confirm id: 7, status: 0xE1 
09:57:57:166 APS-DATA.confirm id: 7, status: 0xE1, match: 0
09:57:57:170 APS-DATA.indication srcAddr: 0x41e2, srcEp: 0x01 dstAddrMode: 2, profile: 0x0104, cluster: 0x0000, lqi: 255, rssi: -56
09:57:57:170 APS-DATA.indication from unknown node 0x41E2
09:57:57:170 ZCL attribute report 0x0000000000000000 for cluster 0x0000, ep 0x01
09:57:57:170 APS-DATA.request id: 7, addrmode: 0x02, addr: 0x41e2, profile: 0x0104, cluster: 0x0000, ep: 0x01 -> 0x01 queue: 1 len: 5 tx.options 0x00
09:57:57:174 APS-DATA.indication srcAddr: 0x41e2, srcEp: 0x00 dstAddrMode: 2, profile: 0x0000, cluster: 0x0000, lqi: 255, rssi: -46
09:57:57:174 APS-DATA.indication from unknown node 0x41E2
09:57:57:174 APS-DATA.request id: 9, addrmode: 0x02, addr: 0x41e2, profile: 0x0000, cluster: 0x8000, ep: 0x00 -> 0x00 queue: 2 len: 12 tx.options 0x04
09:57:57:178 APS-DATA.indication srcAddr: 0x89c2, srcEp: 0x01 dstAddrMode: 2, profile: 0x0104, cluster: 0x0402, lqi: 255, rssi: -34
09:57:57:178 APS-DATA.indication from unknown node 0x00158D000323098F
09:57:57:178 ZCL attribute report 0x00158D000323098F for cluster 0x0402, ep 0x01
09:57:57:192 APS-DATA.confirm id: 4, status: 0x00 SUCCESS
09:57:57:192 APS-DATA.confirm request id: 4 -> confirmed, timeout 38562032
09:57:57:196 APS-DATA.indication srcAddr: 0x0000, srcEp: 0x00 dstAddrMode: 2, profile: 0x0000, cluster: 0x8002, lqi: 255, rssi: 12
09:57:57:196 APS-DATA.indication request id: 4 -> finished
09:57:57:196 APS-DATA.request id: 4 erase from queue
09:57:57:205 APS-DATA.confirm id: 9, status: 0xD0 
09:57:57:255 reconnect network done
09:57:57:269 saved node state in 0 ms
09:57:57:291 sync() in 22 ms
09:57:57:292 REST API plugin shutting down
09:57:57:312 sync() in 5 ms
/run.sh: line 127:   371 Aborted                 (core dumped) deCONZ -platform "${PLATFORM}" --auto-connect=1 --dbg-info="${DBG_INFO}" --dbg-aps="${DBG_APS}" --dbg-otau="${DBG_OTAU}" --dbg-zcl="${DBG_ZCL}" --dbg-zdp="${DBG_ZDP}" --http-port="${API_PORT}" --ws-port="${WEBSOCKET_PORT}" --upnp=0 --dev="${DECONZ_DEVICE}"
```
Device:
Raspberry Pi 4B with 4GB RAM, external MariaDB for Hass. Original Raspberry Power Supply.
I run everything in Docker. 
```
arch | armv7l
-- | --
dev | false
docker | true
hassio | true
os_name | Linux
python_version | 3.7.4
timezone | Europe/Amsterdam
version | 0.101.3
virtualenv | false
```

Before version 0.101 and deconz 3.7, everything works perfect and stable.. Can somebody help me out? Thanks!

**Comment by frenck** [comment] 2019-11-11 09:45
This is a duplicate of #816, let centralize the discussion on finding the root cause for this. 👍

**Closed by frenck** 2019-11-11 09:45 UTC
